### ISSUE TITLE
CPL with multiple CDCIEssenceDescriptors

### ISSUE THREAD

**Issue by pfirth3** [Netflix/photon#144]
I tried to validate a CPL that has two CDCIEssenceDescriptors using IMPAnalyzer and it returned the following error:
"This Composition represented by the ID ae9213b1-01bf-4ffa-b113-a3f6d80ad46d is invalid since the VirtualTrack represented by ID dd48d8f3-
044a-4c2f-9e69-b3b07c3ae866 is not homogeneous based on a comparison of the EssenceDescriptors referenced by its resources in the
Essence Descriptor List, the EssenceDescriptors corresponding to this VirtualTrack in the EssenceDescriptorList are as follows"

The only fields that differ between the two essence descriptors are:
<Id>urn:uuid:8c5a652a-90f5-4647-34d4-6eebc28bd049</Id>
<m:EssenceLength>50</m:EssenceLength>
<m:InstanceID>urn:uuid:0751e8d6-5c0e-4e87-98bb-811c91bd0b95</m:InstanceID> (in JPEG2000SubDescriptor)
<m:InstanceID>urn:uuid:7efa6d75-4e26-4b8c-f53f-c32fe26f16f1</m:InstanceID> (in CDCIDescriptor)
<m:LinkedGenerationID>urn:uuid:f1529db5-a081-4d27-adb2-9661f0f5377e</m:LinkedGenerationID>

I would expect these fields to be different since the essence descriptors come from two different track files. Should this be an error?

**Comment by svenkatrav** [comment]
We have addressed this issue with this commit: [](https://github.com/Netflix/photon/commit/083362f490673286e5ca698111322c3f09bd0e44)

Please give a try with the latest version of Photon (4.1.2) and let us know if the issue is still seen.

**Comment by pfirth3** [comment]
Yes. That seems to fix the issue.
