### ISSUE TITLE
Validating IMF packages with subtitle tracks

### ISSUE THREAD

**Issue by pfirth3** [Netflix/photon#147]
I am having trouble getting a successful validation result when trying to analyze any IMF package that contains a subtitle track. The errors/warnings I get are related to the IMPAnalyzer saying that a CPL resource is not present in the package and that an essence descriptor does not have a match in any track file. 
Based on a test I did with the IMFTrackFileReader, Subtitle essence does not come up as a supported type. It says the only supported types are MainImageEssence, MarkerEssence, MainAudioEssence. Are subtitle tracks really not currently supported? If so, when will support be added?

**Comment by svenkatrav** [comment]
Photon does not support subtitle track currently but we do have a plan to add this support in near-term. We will provide you more accurate timeline once we have the data available.

**Comment by svenkatrav** [comment]
We have added basic support for subtitle sequence in version 4.2.3. This should address essence descriptor related error with subtitle sequence.
