### ISSUE TITLE
Support http://www.smpte-ra.org/schemas/2067-2/2016

### ISSUE THREAD

**Issue by frans-ebu** [Netflix/photon#151]
I noticed Photon does not support/sees as invalid this ApplicationId:
<cc:ApplicationIdentification xmlns:cc="http://www.smpte-ra.org/schemas/2067-2/2016">http://www.smpte-ra.org/schemas/2067-21/2016</cc:ApplicationIdentification>

But it *does* support:
<cc:ApplicationIdentification xmlns:cc="http://www.smpte-ra.org/schemas/2067-2/2013">http://www.smpte-ra.org/schemas/2067-21/2016</cc:ApplicationIdentification>

If it is because it is seen as invalid, I think it is an error.

**Comment by palemieux** [comment]
> <cc:ApplicationIdentification xmlns:cc="http://www.smpte-ra.org/schemas/2067-2/2013">http://www.smpte-ra.org/schemas/2067-21/2016</cc:ApplicationIdentification>

It looks like this combination is not possible since ST 2067-21:2016 requires conformance with ST 2067-2:2016.

**Comment by frans-ebu** [comment]
I did some more testing and it seems the message that 2067-2/2016 & 2067-21/2016 combination was not supported may have been caused by something else. I will try to investigate a bit more.
