### ISSUE TITLE
Exception in IMPAnalyzer

### ISSUE THREAD

**Issue by ManPang** [Netflix/photon#156]
I ran the command C:\Users\Archimedia\Downloads\Photon>java -cp * com.netflix.imflibrary.app.IMPAn
alyzer [path]

where [path] is the folder containing the IMF package

and get the exception:

**Exception in thread "main" java.lang.NoSuchMethodError: com.netflix.imflibrary.s
t0429_9.AssetMap.<init>(Ljava/io/File;)V
        at com.netflix.imflibrary.st0429_9.BasicMapProfileV2MappedFileSet.<init>
(BasicMapProfileV2MappedFileSet.java:89)
        at com.netflix.imflibrary.app.IMPAnalyzer.analyzePackage(IMPAnalyzer.jav
a:154)
        at com.netflix.imflibrary.app.IMPAnalyzer.main(IMPAnalyzer.java:400)**

I then tried the command by specifying a file as the last parameter rather than a path and got the exception:

**Exception in thread "main" java.lang.NoSuchMethodError: com.netflix.imflibrary.u
tils.ResourceByteRangeProvider.getByteRangeAsBytes(JJ)[B
        at com.netflix.imflibrary.app.IMPAnalyzer.getHeaderPartitionPayloadRecor
d(IMPAnalyzer.java:109)
        at com.netflix.imflibrary.app.IMPAnalyzer.validateEssencePartition(IMPAn
alyzer.java:288)
        at com.netflix.imflibrary.app.IMPAnalyzer.analyzeFile(IMPAnalyzer.java:3
10)
        at com.netflix.imflibrary.app.IMPAnalyzer.main(IMPAnalyzer.java:424)**

**Comment by svenkatrav** [comment]
Please check our wiki(https://github.com/Netflix/photon/wiki) on using Photon for analyzing packages on Windows. Please try the following command and let us know if it works:
java -cp build\libs\*; com.netflix.imflibrary.app.PhotonIMPAnalyzer IMP_folder_path

**Comment by ManPang** [comment]
I have done that. I copied Photon into a folder and also added spl4j (although the documentation doesn't mention this). However, I still receive these exceptions. Am I missing other Java libraries? I am using Java 8 Update 111.

**Comment by ManPang** [comment]
Oh and when I try to get the dependencies with gradlew.bat getDependencies, I get the following:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Archimedia\Downloads\photon-master\build.gradle' line: 8

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version:
 '3.1.2']
> Failed to apply plugin [class 'nebula.plugin.release.ReleasePlugin']
   > repository not found: C:\Users\Archimedia\Downloads\photon-master

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

**Comment by svenkatrav** [comment]
Can you verify you followed following steps?
1. Install JDK 

2. Install Git

3. Clone Photon and Build: 
     **git clone https://github.com/Netflix/photon.git**
     .\gradlew.bat clean build
     .\gradlew.bat getDependencies

4. Run IMPAnalyzer
      java -cp build\libs\*; com.netflix.imflibrary.app.IMPAnalyzer src\test\resources\TestIMP\MERIDIAN_Netflix_Photon_161006

**Comment by ManPang** [comment]
I didn't get the dependencies because as I mentioned earlier, attempting to clean or getDependecies resulted in the "Failed to apply plugin [class 'nebula.plugin.release.ReleasePlugin'] repository not found: C:\Users\Archimedia\Downloads\photon-master" error.

I could only work with the binaries which were downloaded from Maven.

**Comment by schakrovorthy** [comment]
ManPang,
Have you been able to get Photon to work now. Please follow the steps mentioned by svenkatrav and circle back with us if you still see issues.
