### ISSUE TITLE
EssenceDescriptors check.

### ISSUE THREAD

**Issue by SuperFish2016** [Netflix/photon#169]
Hello,
There was a error happened when I use photon to check the CPL file.
"ERROR-This Composition represented by the ID b08d310d-25c1-486e-8dd8-25088fe15bd3 is invalid since the VirtualTrack represented by ID **df1b8c5b-4353-4957-ae8d-82e0e94e6ebb** is not homogeneous based on a comparison of the EssenceDescriptors referenced by its resources in the Essence Descriptor List, the EssenceDescriptors corresponding to this VirtualTrack in the EssenceDescriptorList are as follows... "

The ID **df1b8c5b-4353-4957-ae8d-82e0e94e6ebb** is \<TrackId\> in MainAudioSequence.
If there were two Resources in the MainAudioSequence, The ERRORs are always appearing and one audio resource always is OK.

**Comment by SuperFish2016** [comment]
Is it better to use "SourceEncoding" or "TrackFileId" to check the EssenceDescriptor as all "Resources" in the MianAudioSequence have same TrackId.

**Comment by svenkatrav** [comment]
Based on the error description it looks like the two audio resources in the track are failing homogeneity check i.e. essence descriptors of these two resources do not match. Homogeniety check happens only when there are more than one resource in a track. Could you please attach complete error description and also if possible provide CPL with the issue.

**Comment by SuperFish2016** [comment]
@svenkatrav Thank you for your explanation. It is the second resouce issue.
