### ISSUE TITLE
Application#4 (ST2067-40) support?

### ISSUE THREAD

**Issue by cfadamp** [Netflix/photon#171]
Hello,

Is there or will there support for Application#4 (ST2067-40) IMF package validation? CPL validation and/or track file validation? Our App#4 CPLs failed on the validation.

Attached is our experimental sample CPL for testing purposes:
[CPL_App4CinemaM_FTR-1_C_EN-XX_HU-NR_71_QHD_20170103_OV.TXT](https://github.com/Netflix/photon/files/684407/CPL_App4CinemaM_FTR-1_C_EN-XX_HU-NR_71_QHD_20170103_OV.TXT)

(Note: I could not upload files with XML or ZIP extension...)

Thanks,

**Comment by svenkatrav** [comment]
Currently Photon does not support Application#4 CPL. We can enable Photon to validate IMF CPL (st2067-3) and core constraints (st2067-2) without validating any application level constraints for Application#4. Could you please share sample IMF package for Application#4? This will be very useful for our development effort.

**Comment by svenkatrav** [comment]
Photon version 4.3.4 allows validating CPL and core constraint checks for unsupported application types.
