### ISSUE TITLE
Audio tracks containing GroupOfSoundfieldGroupsLabelSubDescriptor causing Photon to report an error

### ISSUE THREAD

**Issue by go4shoe** [Netflix/photon#178]
We added the audio sub-descriptor GroupOfSoundfieldGroupsLabelSubDescriptor.

The sub-descriptor is defined in SMPTE ST 377-4:2012; 6.6 GroupOfSoundfieldGroupsLabelSubDescriptor; Page 13

Previously "Photon" was crashing when encountering the GroupOfSoundfieldGroupsLabelSubDescriptor.

Now Photon gracefully fails and considers the GroupOfSoundfieldGroupsLabelSubDescriptor as unknown.

But you are generating an error:

14 Feb 2017 17:54:08,318 [ERROR] [IMFTrackFileReader]: ERROR-Error code : STRONG_REFERENCE_NOT_FOUND - Strong Reference target urn:uuid:970a12e8-e335-1343-bb5f-9c142c4f276f is not found at Type SubDescriptorStrongReference at Element SubDescriptors

because Photon can't resolve the strong reference to the GroupOfSoundfieldGroupsLabelSubDescriptor.

We consider GroupOfSoundfieldGroupsLabelSubDescriptor as valid and accoring to SMPTE ST 377-4:2012.

Please advice.

IMF package:

https://drive.google.com/drive/folders/0B1K1m-YmE28DMGFrbmZZa0JjUWM

Thanks
Markus.

P.S.: we are aware that our audio file has two unrelated errors: missing langauge and missing MCATitle, MCATitleVersion, MCAAudioContentKind, MCAAudioElementKind

**Comment by svenkatrav** [comment]
Thanks for sharing the package and letting us know about the issue. Version 4.3.6 has the fix.
