### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by 9731756162** [Netflix/photon#185]
Build file 'D:\Photon_New\photon-4.4.0\build.gradle' line: 8

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.1.2']
> Failed to apply plugin [class 'nebula.plugin.release.ReleasePlugin']
   > repository not found: D:\Photon_New\photon-4.4.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.159 secs

**Comment by abing0214** [comment]
I got the same error and found a solution here:
https://github.com/Netflix/Priam/issues/401

Clone the repository, copy the ".git" (hidden) folder to your "D:\Photon_New\photon-4.4.0\".
Then try build.

**Comment by cconcolato** [comment]
Closing this issue as there was a proposed solution and no response. Reopen the issue if there is still a problem.
