### ISSUE TITLE
Failed to connect to github.com port 443: Bad access

### ISSUE THREAD

**Issue by 9731756162** [Netflix/photon#186]
when i am trying to clone a netflix photon project using this url https://github.com/Netflix/photon.git/ iam getting error as Failed to connect to github.com port 443: Bad access. please provide a solution

**Comment by tcase-netflix** [comment]
Once your public key is added to github, you should be able to clone the
repo by running the command:

git clone git@github.com:netflix/photon.git

Terry

**Comment by 9731756162** [comment]
@tcase-netflix how to add public key to github

**Comment by MisterLoveG** [comment]
This may be a anti-virus issue see this post:
https://stackoverflow.com/questions/44600793/error-when-clone-push-git-repos-443-bad-access-but-no-proxy-used

**Comment by kalengi** [comment]
In my case it was a firewall issue. Enabling Git for Windows on the firewall solved the problem.

**Comment by SuprunOleh** [comment]
i also had a problem with firewall

**Comment by developer501** [comment]
@kalengi @SuprunOleh - How do you enable Git for Windows?

**Comment by jamesta696** [comment]
How do you enable Git on Windows Firewall?

**Comment by Eddiex79** [comment]
Thank you for helping guys.

**Comment by Tripantoro** [comment]
> In my case it was a firewall issue. Enabling Git for Windows on the firewall solved the problem.

Thank You... Oh My Zsh begin download after my TinyWall has disable firewall... and successful installed. ❤
