### ISSUE TITLE
JDK-7 support version ?

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [Netflix/photon#19]
I'm tring to build Photon using open-jdk-7 and I obtain this error message:
```
./gradlew build
Inferred project: Photon, version: 0.2.0-SNAPSHOT
[buildinfo] Not using buildInfo properties file for this build.
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> invalid source release: 1.8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

After installing open-jdk-8 the build was performed correctly.
I don't know what's the better, keep the compatibility with java-7 or remove it from the README ("Although Photon can be built using JDK-7, it is recommended to use JDK-8 or later.")

**Comment by schakrovorthy** [comment]
Marc,

Thanks for pointing this out. We explicitly state SourceCompatibility=1.8 in the gradle build file, we should've and now have cleared the ambiguity in the ReadMe, it should make it into the next release. Hope this helps.

Regards
Sreeram

**Comment by MarcAntoine-Arnaud** [comment]
Thanks for this quick answer, an the creation of the issue #20. 
Of course an update of the readme is a right answer :+1:

**Comment by schakrovorthy** [comment]
Marc, release 0.1.2 to Maven Central will have the updated ReadMe. Closing this issue as addressed.
