### ISSUE TITLE
ASSETMAP.xml: Segment length in filenames

### ISSUE THREAD

**Issue by IMFTool** [Netflix/photon#192]
v4.4.3 erroneously complains about path segments with invalid length:
```
08 May 2017 13:49:02,518 [ERROR] [IMPAnalyzer]: 		ERROR-The Asset path 418519_TerraX_MythosWolfskindMogliUndDieWildenKinder_InternationaleFassung_deu_clean_stereo_51_MundE_stereo.mxf has following path segments with invalid length: 
418519_TerraX_MythosWolfskindMogliUndDieWildenKinder_InternationaleFassung_deu_clean_stereo_51_MundE_stereo.mxf
 [Photon version: 4.5.0-SNAPSHOT]
```
  Segment length is 112, which is < 128 (ST 2067-2:2016 L.3).
ASSETMAP.xml attached.
[ASSETMAP.xml.zip](https://github.com/Netflix/photon/files/983341/ASSETMAP.xml.zip)

**Comment by svenkatrav** [comment]
Photon conforms AssetMap as per SMPTE ST 429-9:2014 Annex A Basic Map Profile v2 which has limit of 100 characters per path segment length.
IMF HTTP Map Profile(ST 2067-2:2016 L.3) is for retrieving resources based on http" or "https" scheme and not for direct attached storage.

**Comment by IMFTool** [comment]
Acknowledged, thx!
