### ISSUE TITLE
Dolby HDR IMF 

### ISSUE THREAD

**Issue by SuperFish2016** [Netflix/photon#199]
hello,
I have encountered some errors when validating the Dolby HDR IMF CPL.
-------------------------------------------------------------------------------------------------------------------------
29 Jul 2017 10:02:25,525 [INFO ] [Composition]: CompositionPlaylist Document has 8 errors and 0 warnings
29 Jul 2017 10:02:25,528 [ERROR] [Composition]: ERROR-EssenceDescriptor with ID feee0755-8150-411a-b39d-8e19b7ec89e1 is missing J2CLayout in JPEG2000SubDescriptor [Photon version: 4.6.0-SNAPSHOT]
29 Jul 2017 10:02:25,528 [ERROR] [Composition]: ERROR-EssenceDescriptor with ID feee0755-8150-411a-b39d-8e19b7ec89e1 has invalid combination of ComponentMinRef/BlackRefLevel(0)-ComponentMaxRef/WhiteRefLevel(1023)-PixelBitDepth(0) in Image Essence Descriptor [Photon version: 4.6.0-SNAPSHOT]
29 Jul 2017 10:02:25,528 [ERROR] [Composition]: ERROR-EssenceDescriptor with ID feee0755-8150-411a-b39d-8e19b7ec89e1 has invalid ColorPrimaries as per APPLICATION_2E_C

OMPOSITION_TYPE [Photon version: 4.6.0-SNAPSHOT]
29 Jul 2017 10:02:25,528 [ERROR] [Composition]: ERROR-EssenceDescriptor with ID feee0755-8150-411a-b39d-8e19b7ec89e1 has invalid TransferCharacteristic as per APPLICATION_2E_COMPOSITION_TYPE [Photon version: 4.6.0-SNAPSHOT]
29 Jul 2017 10:02:25,528 [ERROR] [Composition]: ERROR-EssenceDescriptor with ID feee0755-8150-411a-b39d-8e19b7ec89e1 has invalid ColorPrimaries(Unknown)-TransferCharacteristic(Unknown)-CodingEquation(None) combination as per APPLICATION_2E_COMPOSITION_TYPE [Photon version: 4.6.0-SNAPSHOT]
29 Jul 2017 10:02:25,528 [ERROR] [Composition]: ERROR-EssenceDescriptor with ID feee0755-8150-411a-b39d-8e19b7ec89e1 has invalid ContentKind(1) indicated by the ContainerFormat as per APPLICATION_2E_COMPOSITION_TYPE [Photon version: 4.6.0-SNAPSHOT]
29 Jul 2017 10:02:25,528 [ERROR] [Composition]: ERROR-EssenceDescriptor with ID feee0755-8150-411a-b39d-8e19b7ec89e1 invalid PixelBitDepth(0) for Color(Unknown) as per APPLICATION_2E_COMPOSITION_TYPE [Photon version: 4.6.0-SNAPSHOT]
29 Jul 2017 10:02:25,529 [ERROR] [Composition]: ERROR-EssenceDescriptor with ID feee0755-8150-411a-b39d-8e19b7ec89e1 has Invalid Quantization(Unknown) for ColorModel(RGB) as per APPLICATION_2E_COMPOSITION_TYPE [Photon version: 4.6.0-SNAPSHOT]
---------------------------------------------------------------------------------------------------------------------
[mxf_cpl.zip](https://github.com/Netflix/photon/files/1184600/mxf_cpl.zip)

 I'd like to know if Photon has supported the Dolby HDR IMF(mxf created by Dolby SIDK).
attachment is the resulting CPL file created by IMFTrackFileCPLBuilder with the dolby vision mxf file.

**Comment by svenkatrav** [comment]
Photon supports validation of Dolby HDR IMF. However IMFTrackFileCPLBuilder does not have extensive application support and do not recommend using it.
