### ISSUE TITLE
OPL validation fails if aliases are defined in header

### ISSUE THREAD

**Issue by cfadamp** [Netflix/photon#201]
Photon fails if "alias" is defined in the header. Validation fails even if I don't use any alias handle later. I read the corresponding standard documents (ST2067-100:2014 Section 8) and I don't know what I am doing wrong. Could you please check?

Attached are a working and a failing OPL file with Photon logs.
[OPL_files_and_logs.zip](https://github.com/Netflix/photon/files/1215547/OPL_files_and_logs.zip)

Thank you in advance,
Adam

**Comment by svenkatrav** [comment]
Hi Adam,

Thanks for pointing this out. Photon version 4.5.6 has the fix for using alias as macro input. This should fix many of the errors that you are seeing. However there is still one issue with the OPL where it is missing "alias/" prefix for image-scale-1 macro. 

Thanks,
Subbu

**Comment by cfadamp** [comment]
Hi Subbu,

I just tried it and it worked for me without errors.

Thanks,
Adam
