### ISSUE TITLE
OPL validation error

### ISSUE THREAD

**Issue by pfirth3** [Netflix/photon#204]
[OPL_6abac94f-d016-45a0-9e36-13b4ccad71a0.zip](https://github.com/Netflix/photon/files/1240253/OPL_6abac94f-d016-45a0-9e36-13b4ccad71a0.zip)
I get the following error for my attached OPL:

Line Number : 10 - cvc-complex-type.2.4.b: The content of element 'MacroList' is not complete. One of '{"http://www.smpte-ra.org/schemas/2067-
100/2014":Macro}' is expected. [Photon version: 4.6.0-SNAPSHOT]

Is there a way to put in a macro that does nothing? This is just a stub OPL with no macros intended to be in it.

**Comment by svenkatrav** [comment]
You can use PresetMacro as defined in ST2067-100 Annex B.

Example: https://github.com/Netflix/photon/blob/master/src/test/resources/TestIMP/OPL/OPL_8cf83c32-4949-4f00-b081-01e12b18932f_simple.xml

**Comment by pfirth3** [comment]
Thanks!
