### ISSUE TITLE
how to run netflix photon command

### ISSUE THREAD

**Issue by robina80** [Netflix/photon#205]
hi all, 

i cd into the "c:\photon" in command prompt

then i run this command but i get this error - 

C:\photon>java -cp build\libs\*; com.netflix.imflibrary.app.IMFTrackFileReader imf_track_file_path E:\_SHARE\_IMF\Meridian_IMF_UHD_23976_en_L_R_C_Lfe_Ls_Rs_Lt_Rt_MOL_OV

01 Sep 2017 13:25:47,602 [ERROR] [IMFTrackFileReader]: File C:\photon\imf_track_file_path does not exist

what am i doing wrong

many thanks,

rob

**Comment by MarcAntoine-Arnaud** [comment]
Hello,

You've just pass 2 arguments `imf_track_file_path` and `E:_SHARE_IMF\Meridian_IMF_UHD_23976_en_L_R_C_Lfe_Ls_Rs_Lt_Rt_MOL_OV`.

just try:
```java -cp build\libs*; com.netflix.imflibrary.app.IMFTrackFileReader imf_track_file_path E:/Meridian_IMF_UHD_23976_en_L_R_C_Lfe_Ls_Rs_Lt_Rt_MOL_OV```

Best regards,
Marc-Antoine

**Comment by robina80** [comment]
im doing this on windows and the working directory is - 

E:\_SHARE\_IMF\Meridian_IMF_UHD_23976_en_L_R_C_Lfe_Ls_Rs_Lt_Rt_MOL_OV

but when i run it i get this - 

C:\photon>java -cp build\libs\*; com.netflix.imflibrary.app.IMFTrackFileReader imf_track_file_path E:\_SHARE\_IMF\Meridian_IMF_UHD_23976_en_L_R_C_Lfe_Ls_Rs_Lt_Rt_MOL_OV

01 Sep 2017 13:47:59,434 [ERROR] [IMFTrackFileReader]: File C:\photon\imf_track_file_path does not exist

so i delete the "imf_track_file_path"

and now i get this error - 

C:\photon>java -cp build\libs\*; com.netflix.imflibrary.app.IMFTrackFileReader E:\_SHARE\_IMF\Meridian_IMF_UHD_23976_en_L_R_C_Lfe_Ls_Rs_Lt_Rt_MOL_OV
01 Sep 2017 13:49:40,890 [ERROR] [IMFTrackFileReader]: Usage:
com.netflix.imflibrary.app.IMFTrackFileReader <inputFilePath> <workingDirectory>

i dont get this

**Comment by MarcAntoine-Arnaud** [comment]
Hi again,

Sorry regarding the source code, this App require 2 arguments.
The second argument is the IMP root folder.
The first one look to be the path of the selected CPL (with tracks to validate), as IMP can have many CPLs.

Can you try that ?

Marc-Antoine

**Comment by robina80** [comment]
i was running the wrong command -

java -cp build\libs\*; com.netflix.imflibrary.app.IMPAnalyzer IMP_folder_path

so -

java -cp build\libs\*; com.netflix.imflibrary.app.IMPAnalyzer E:\SHARE_IMF\Meridian_IMF_UHD_23976_en_L_R_C_Lfe_Ls_Rs_Lt_Rt_MOL_OV

**Comment by MarcAntoine-Arnaud** [comment]
Okay made sense ;-) the most use one !
