### ISSUE TITLE
Audio duration is not an integer length for video frame rates 29.97 or 59.94

### ISSUE THREAD

**Issue by go4shoe** [Netflix/photon#209]
If I use 30,000/1001 or 60,000/1001 video with 48 kHz audio I can only make the audio stream the exact duration of the video stream if the video frame count is divisible by 5.

It seems a fairly harsh rule considering that video may consists of multiple segments.
 
For example - if my video consists of multiple segments then all video segments have to be aligned on a 5 frame boundary.

Example for one segment:

Video 29.97 with 5,378 frames would require at
audio 48 kHz with 8,613,404.8 samples.
I obviously can not encode 0.8 audio samples.

Currently my choices: add two video frames to get to 5,380 or remove three video frames to get to 5,375.

What do you guys think about having the audio integer sample count within +/- one sample of the fractional calculated audio sample count?

**Comment by palemieux** [comment]
@go4shoe Why not use markers instead of segments? In other words, where did the requirements for segments come from? Segments are intended to be essentially independent parts of the timeline. 

> What do you guys think about having the audio integer sample count within +/- one sample of the fractional calculated audio sample count?

This was ruled out from Application 2/2E as yielding unpredictable results.

**Comment by go4shoe** [comment]
Thanks for your response and pointing me towards the correct specification (Application 2/2E).
I am not sure how markers are going to help me. If me video consists of two individual files 29.97 fps and both files have a frame count that is unaligned to 5.

**Comment by palemieux** [comment]
> I am not sure how markers are going to help me. If me video consists of two individual files 29.97 fps and
> both files have a frame count that is unaligned to 5.

Individual resources can have a duration that is not a multiple of 5. It is the sequence whose duration must be a multiple of 5. For instance, the following is permitted:

```
Segment
|
+-- Image Sequence
    |
    +-- Track File Resource
    |   |
    |   + duration = 299
    |
    +-- Track File Resource
    |    |
    |    + duration = 299
    |
    Image Sequence
    |
    +-- Track File Resource (black frames)
       |
       + duration = 2
```

**Comment by go4shoe** [comment]
Thanks again for your inside - I suspect a typo in your above comment:

Do mean the "Segment" must be a multiple of 5?

Your above comment says the "Sequence" must be 5 aligned.

**Comment by cconcolato** [comment]
Closing this issue as it seems that your problem is with the spec.
Photon does verify, per the spec, that the durations of sequences in a segment match, see https://github.com/Netflix/photon/blob/master/src/main/java/com/netflix/imflibrary/st2067_2/IMFCoreConstraintsChecker.java#L310
