### ISSUE TITLE
Validation error of packages with multiple PKLs

### ISSUE THREAD

**Issue by dtatut** [Netflix/photon#210]
V4.6 seems to find errors in supplemental CPLs when an ASSETMAP contains multiple PKLs, with each PKL referencing a CPL (and relevant assets).

**Comment by cconcolato** [comment]
I tried to reproduce this issue but could not. Can you verify with the latest version and if it fails, provide an example package?

**Comment by fschleich** [comment]
Please re-open if still an issue.
