### ISSUE TITLE
EssenceDescriptor Equivalence Check

### ISSUE THREAD

**Issue by pfirth3** [Netflix/photon#216]
We have a supplemental package that has video assets that were created with two different J2K encoders. The only difference between the essence descriptors for these two assets is the CodingStyleDefault and QuantizationDefault. These values are different even though the exact same settings were used to create the video assets. All other parameters in the JPEG2000SubDescriptor are the same. I noticed in the code that there is a list of fields that are ignored when checking for essence descriptor equivalence. Should these fields be added to the ignore list when checking for essence descriptor equivalence?

**Comment by svenkatrav** [comment]
This is fixed in 4.5.11.
