### ISSUE TITLE
How can I create an IMF?

### ISSUE THREAD

**Issue by lizhuangzi** [Netflix/photon#220]
Thank you for you provide code, and I am a beginner of this area. I want to know how to create an IMF? what file I should need? a .mp4 video?   and what API should I call?  Can you provide a IMF for my test?

**Comment by MarcAntoine-Arnaud** [comment]
Hi,

Photon is not a tool to create IMF packages.
It's a Netflix specific validator.
You can see other open-source projects like AsDCPLib to create IMF package.

Marc-Antoine

**Comment by svenkatrav** [comment]
@lizhuangzi Photon does not support creating IMF packages. @MarcAntoine-Arnaud Just to clarify, Photon is an implementation of IMF standard as described in the readme below and not a Netflix specific validator.
https://github.com/Netflix/photon/blob/master/README.md .

**Comment by badmans** [comment]
@lizhuangzi The Netflix Partner Help Center provides information on IMF specifications, workflows, and creation tools (Technology Resources). [](https://partnerhelp.netflixstudios.com/hc/en-us)

The Netflix Tech Blog has several articles explaining IMF. [](https://medium.com/netflix-techblog/imf-a-prescription-for-versionitis-e0b4c1865c20)

Also, SMPTE offers a comprehensive online training course on IMF Essentials. [](https://www.smpte.org/education/courses/imf)

**Comment by MarkusPfundstein** [comment]
I can help you with that. Shoot me a PM and we can get started. I developed with my partner Andy Rosen a online tool.

With best regards,
Markus

**Comment by cconcolato** [comment]
Closing this issue as it does not require any change to Photon and your initial request seems to have been answered.
