### ISSUE TITLE
Photon ignores the absence of ContentVersion Id elements

### ISSUE THREAD

**Issue by dtatut** [Netflix/photon#227]
In SMPTE 2067-2:2016, section 6.7, the presence of at least one ContentVersion element is mandatory. However, in SMPTE ST 2067-3:2016, section 6.1, the XSD defines the ContentVersionList element as optional:

<xs:element name="ContentVersionList" minOccurs="0">

Photon seems to rely on the schema only and ignores the mandatory aspect of a minimum of one ContentVersion element in the CPL, as stated in App #2/#2E, App #4 and App #5

**Comment by MarcAntoine-Arnaud** [comment]
I don't see any restriction into App 2 and 2E regarding this field.
I have checked 2064-20:2016 and 2064-21:2016, no minimal occurence are mentioned.

Regarding the App 4, it requires 1 occurence, but Photon don't support this application right now.
So for me it's a normal behavior.

**Comment by dtatut** [comment]
It's in SMPTE 2067-2:2016, section 6.7

2067-20:2016, section 4.1 says: "All provisions of SMPTE ST 2067-2 shall apply."

While SMPTE ST 2067-3:2016, section 6.1 creates the confusion with the optional nature of the ContentVersionList element.

In other words App 2 must follow the core constraints in full, no choice. If Photon validates App 2/2E then it must complain in the absence of the ContentVersionList.

Same goes with App 4 and 5, because of the core constraints. Photon should detect that anyway, regardless of the support of App 4 or 5.

**Comment by MarcAntoine-Arnaud** [comment]
So do you think it can be great to open the discussion to change that in the 2067-3 ?
It needs to update the schema with:
```xml
<xs:element name="ContentVersionList" minOccurs="1">
```
which should fix the misunderstanding.

**Comment by remia** [comment]
I'm looking into App #4 support right now and face the same issue.

As I see it, the `ContentVersionType` class object is only available through the generated classes from the _ST2067-2-2013_ and _ST2067-2-2016_ schemas. I wonder how we can easily import this as a field in the `IMFCompositionPlaylistType` class, probably must redefine this type manually as a non-auto generated class ?

Not sure what's the correct way to proceed here.

**Comment by fschleich** [comment]
Closing as presence of ContentVersion is no longer required per ST 2067-2:2020.
