### ISSUE TITLE
Select Applications valid in the current scope

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [Netflix/photon#229]
Hi all,

As I work on integration of the TSP2121 validation, it will add a new codec ProRes to support.
I suppose (as Netflix and for other persons) it can be interesting to provide an IMPAnalyzer with an option to select which Application(s) or not are supported in the analyse.
Like that by default it will support all Applications (App2, App2e, TSP 2121 and maybe App 4 and 5 in the future).

Do you think it can be integrated ? Can I purpose a PR to do it ?

Thanks,
Marc-Antoine

**Comment by cconcolato** [comment]
Closing as discussion seems to happen in #242
