### ISSUE TITLE
Error when building with gradlew ('nebula.netflixoss')

### ISSUE THREAD

**Issue by marcrleonard** [Netflix/photon#233]
Running on Ubuntu 18, I ran 
`sudo ./gradlew clean`

and got:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/marc/Desktop/photon-master/build.gradle' line: 8

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.1.2']
> Failed to apply plugin [class 'nebula.plugin.release.ReleasePlugin']
   > repository not found: /home/marc/Desktop/photon-master

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 26.104 secs

```

It seems as though it cannot find the `id: 'nebula.netflixoss', version: '3.1.2'` dependency.

**Comment by MarcAntoine-Arnaud** [comment]
Hi,

Take care about running build/clean commands in root ... Lot of things can append !

Regarding the issue, you need to clone the project via `git clone` command. taking the zip from the master branch will not work as you can see.

**Comment by marcrleonard** [comment]
I found the issue.
I had downloaded the .zip of the repo rather than doing a git clone. In doing so, I let it unzip to it's natural file location of `~/photon-master`. For some reason this tripped it up. When I did a git clone of the repo > `~/photon` it worked properly.

**Comment by marcrleonard** [comment]
Indeed, thank you Marc! I had indeed originally tried it sans sudo... This was my seconds attempt.
