### ISSUE TITLE
Photon creates error if there is no traditional audio track, only IAB track in the composition timeline

### ISSUE THREAD

**Issue by cfadamp** [Netflix/photon#266]
If I create a CPL with no traditional audio track, only IAB as audio, then I get the following error:

ERROR-The Composition represented by Id 886290e6-221e-4eda-9be9-999b49ad1df9 does not contain a single audio essence in its first segment, one or more is required [Photon version: 4.7.0-SNAPSHOT]

Is it intended? Or should photon allow CPLs with only IAB as audio?
[cpl_with_only_iab.txt](https://github.com/Netflix/photon/files/3901919/cpl_with_only_iab.txt)

Thanks,
Adam

**Comment by cconcolato** [comment]
This is intended. There are discussions to publish a new version of the standard to drop the requirement for audio but that version is not yet published. Note that the CPL namespace would probably change in that case. 

I'm closing the ticket, please reopen if you have additional information.
