### ISSUE TITLE
IMSC 1.1 profiles missing

### ISSUE THREAD

**Issue by IMFTool** [Netflix/photon#283]
The following IMSC 1.1 profile URIs should probably be added to the checks of `NamespaceURI` item of the Timed Text descriptor (only for IMF 2020 compositions):
`http://www.w3.org/ns/ttml/profile/imsc1.1/text`
`http://www.w3.org/ns/ttml/profile/imsc1.1/image`
`urn:ebu:tt:distribution:2014-01`
`http://www.w3.org/ns/ttml/profile/sdp-us`

https://github.com/Netflix/photon/blob/3f4677e92be1a4e85bc2f4f3a1df31329d0fbb29/src/main/java/com/netflix/imflibrary/IMFConstraints.java#L52

**Comment by IMFTool** [comment]
The related PR #344 has been updated.

**Comment by fschleich** [comment]
Thanks Wolfgang! I merged the changes, and released as [v4.10.6](https://github.com/Netflix/photon/tree/v4.10.6).
