### ISSUE TITLE
Upload to Maven Central

### ISSUE THREAD

**Issue by boris-petrov** [Netflix/photon#288]
[Bintray+JCenter is being terminated](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) so the path forward would be to use Maven Central. There is a nice summary on what must be done [here](https://mvysny.github.io/jcenter-is-dead/).

**Comment by palemieux** [comment]
FYI. Example of central deployment magic here:

https://github.com/sandflow/regxmllib/blob/a3caf4f864f024847a97b0e827dc458e9084b06a/pom.xml#L146

**Comment by boris-petrov** [comment]
I believe this has been resolved. Thanks!
