### ISSUE TITLE
Warning: Unknown Group UL

### ISSUE THREAD

**Issue by jhwwoods** [Netflix/photon#295]
Hello,
   I am fairly new to using Photon, so please forgive me if this is a stupid question.

We have been using the integrated Davinci Resolve 17.2.2 Photon tool and we are consistently seeing the following warning on our IMF's and was wondering what it indicates:

13 Sep 2021 18:14:39,038 [INFO ] [IMPAnalyzer]: ==========================================================================
13 Sep 2021 18:14:39,048 [INFO ] [IMPAnalyzer]: Analyzing IMF package trainingerin_ep103_imf_dovi_p3d65_ST2084_20210913_3840x2160_OV
13 Sep 2021 18:14:39,048 [INFO ] [IMPAnalyzer]: ==========================================================================
13 Sep 2021 18:14:40,834 [INFO ] [IMPAnalyzer]: VIDEO_c9186f06-1056-4c41-b4eb-962a5fe1f69e.mxf has no errors or warnings
13 Sep 2021 18:14:40,834 [INFO ] [IMPAnalyzer]: OPL_f01cd096-ac32-4d2a-8336-71b2bbfa4d5d.xml has no errors or warnings
13 Sep 2021 18:14:40,834 [INFO ] [IMPAnalyzer]: PKL_205df917-1f24-4a0d-93b3-058c5261babe.xml has no errors or warnings
13 Sep 2021 18:14:40,834 [INFO ] [IMPAnalyzer]: AUDIO_0958b87d-c0fc-4425-89a6-e0d0b0aa821d.mxf has no errors or warnings
13 Sep 2021 18:14:40,835 [INFO ] [IMPAnalyzer]: CPL_43c92ab3-f0e1-4c81-a2df-2a0c780317bf.xml has no errors or warnings
13 Sep 2021 18:14:40,835 [INFO ] [IMPAnalyzer]: ASSETMAP.xml has no errors or warnings
13 Sep 2021 18:14:40,835 [INFO ] [IMPAnalyzer]: AUDIO_412d87e3-dd0e-42d6-9646-7ba5c04ebb82.mxf has no errors or warnings
13 Sep 2021 18:14:40,835 [INFO ] [IMPAnalyzer]: 

13 Sep 2021 18:14:40,835 [INFO ] [IMPAnalyzer]: ==========================================================================
13 Sep 2021 18:14:40,835 [INFO ] [IMPAnalyzer]: Virtual Track Conformance
13 Sep 2021 18:14:40,835 [INFO ] [IMPAnalyzer]: ==========================================================================
13 Sep 2021 18:14:40,838 [INFO ] [IMPAnalyzer]: CPL_43c92ab3-f0e1-4c81-a2df-2a0c780317bf.xml Virtual Track Conformance has 0 errors and 1 warnings
13 Sep 2021 18:14:40,838 [WARN ] [IMPAnalyzer]: 		WARNING-Error code : UNKNOWN_GROUP - Unknown Group UL urn:smpte:ul:060e2b34.02530105.0e090607.01010103 [Photon version: 4.8.0]

Any help is much appreciated.
Thank you!

**Comment by fschleich** [comment]
Dolby Vision Picture Trackfiles contain private metadata labels that are not documented in the SMPTE register and therefore not recognized by Photon. So this warning is expected and can be ignored. 

SMPTE just published a RDD that documents this specific MXF wrapping (and the ULs), so hopefully the labels will find their way into the official register to resolve this warning.

**Comment by jhwwoods** [comment]
Hi Florian!
    That's great. I'll pass this on.
Thank you for the immediate response.
