### ISSUE TITLE
Not reporting missing VideoLineMap element

### ISSUE THREAD

**Issue by fschleich** [Netflix/photon#296]
Photon currently does not report an error for the attached CPL (or the complete package), even though the VideoLineMap element is missing from the CDCI Descriptor.

Even though the element "shall be ignored" according to ST 2067-20:2016, VideoLineMap is a Best Effort element per ST 377-1:2011 Section F.4.1 Generic Picture Essence Descriptor. The element shall therefore be present in the encoded file and an error should be raised.

[CPL.xml.txt](https://github.com/Netflix/photon/files/7516448/CPL.xml.txt)

**Comment by cfadamp** [comment]
please assign to me

**Comment by danielhdz13-netflix** [comment]
From a cursory glance, a property annotated with `@MXFProperty` can be added to the CDCI Descriptor [class](https://github.com/Netflix/photon/blob/d3cc2eefe06e0c885892c5f73ef13d100df8b36f/src/main/java/com/netflix/imflibrary/st0377/header/CDCIPictureEssenceDescriptor.java#L35). Other relevant classes might be MXFPropertyPopulator, and StructuralMetadata.
