### ISSUE TITLE
Getting a wrong Essence SampleRate Error for Interlaced ProRes content

### ISSUE THREAD

**Issue by HaukeHarms** [Netflix/photon#331]
For ProRes MXF files the edit rate is not doubled in case of interlaced in contrast to J2k material. This has to do with the fact that the fields are stored together in ProRes and separately in J2K.

[CPL_0.txt](https://github.com/Netflix/photon/files/9673297/CPL_0.txt)

**Comment by palemieux** [comment]
Duplication of #369
