### ISSUE TITLE
What is this project in simple terms?

### ISSUE THREAD

**Issue by abitrolly** [Netflix/photon#351]
### Why I am asking this here?

I am trying to organize the chaos of moving files while working on a zero budget movie. File formats, how they should be named, where should be placed, moved down the pipeline and versioned. From Blender work on movie pipelines I discovered [Tears of Steel packed into DCP](http://download.blender.org/demo/movies/ToS/ToS_4k_DCP.zip) format, which seems to be used for delivering movies to cinemas. I got really excited, but I couldn't evaluate if the DCP format is suitable for iterative work on movies from like drafting a scenario to recombining the footage into actual screen picture. So I tried to ask people what Netflix production pipeline looks like (because it's like most digitally advanced movie "studio" with awesome open source contributions), but I have no contacts there and attempts to connect through LinkedIn were not successful (my [profile building skills](https://www.linkedin.com/in/anatolibabenia/) is a joke).

### Where I found this project?

Then I discovered https://netflix.github.io/ and among links of various Netflix projects, this one looked like something related to movie creation pipeline.

### "core constraints `st2067-2:2013 `" doesn't speak anything to me

I totally get the connection between Java, XML and PDF based standards in industrial software world. However, as a hacker I don't appreciate the [appeal to authority](https://yourlogicalfallacyis.com/appeal-to-authority) and prefer to read why things are made certain way, instead of wandering through the jungles of nomenclature abbreviations and digits only to discover few weeks later that guys and girls forgot to define milliseconds to audio timestamps, and it is now impossible to sync files just based on standard meta data. I am not sure if this project is the right place to seek that wisdom, but I have to ask.

What problem does this project solve?
How efficient it solves it?
Are there any alternatives? (like in Blender world)

Thanks. Sorry if it sounds strange, rude, out of place and offtopic.

**Comment by cconcolato** [comment]
As indicated in the README, "Photon is a Java implementation of the Interoperable Master Format (IMF) standard." If you want to understand more about IMF I suggest you have a look at the resources at https://www.imfug.com/

**Comment by abitrolly** [comment]
@cconcolato thanks for the link. I haven't seen it. Sent #352 to add it to README.

This page https://comments.telestream.net/2016/02/overview-interoperable-master-format/ talks that IMF is evolution of DCP, which is the last mile problem, while I am more interested in exchanging WIP movie data. Found https://partnerhelp.netflixstudios.com/hc/en-us now reading if there is anything open source there.
