### ISSUE TITLE
Handle MXF string termination to avoid incorrect validation errors

### ISSUE THREAD

**Issue by thomasheritage** [Netflix/photon#372]
MXF Header Metadata string properties that contain a null character should be trimmed. Currently, the terminating null character (and any subsequent characters) are included in the string used by Photon for validation, resulting in incorrect error reports such as:

```
[main] ERROR com.netflix.imflibrary.app.IMPAnalyzer -           ERROR-Language Code ([0x656e2d474200, en-GB.]) in SoundFieldGroupLabelSubdescriptor in the IMFTrackfile represented by ID ac4aaec3-a55c-48d0-a806-6cb92888ab3a is not RFC5646 compliant [Photon version: 4.10.0-SNAPSHOT]
```

**Comment by thomasheritage** [comment]
This looks like the same as was discussed in #196 (which is closed)

**Comment by fschleich** [comment]
@thomasheritage - thanks for creating the PR! Would you be able to share a sample file that demonstrates the issue?

**Comment by thomasheritage** [comment]
The MXF file in this ZIP demonstrates the issue:
[AUDIO_05a22e3f-b79c-472a-81da-f806469c8574.zip](https://github.com/user-attachments/files/16820704/AUDIO_05a22e3f-b79c-472a-81da-f806469c8574.zip)
