### ISSUE TITLE
HeaderPartition ignores found RGBAPictureEssenceDescriptor when constructing interchangeObjectsMap 

### ISSUE THREAD

**Issue by janbella** [Netflix/photon#59]
Suppose having the following code:  

File inputFile = new File("pictures.mxf");
File workingDirectory = Files.createTempDirectory(null).toFile();
ResourceByteRangeProvider resourceByteRangeProvider = new FileByteRangeProvider(inputFile);
MXFEssenceReader mxfEssenceReader = new MXFEssenceReader(workingDirectory, resourceByteRangeProvider);
Assert.assertEquals(mxfEssenceReader.getEssenceTypes().size(), 1);

Suppose pictures.mxf contains image essence, nut no KLV corresponding to CDCIPictureEssenceDescriptor, only that corresponding to RGBAPictureEssenceDescriptor. 

The last assert fails, mxfEssenceReader claiming there are no essence types in the .mxf. I suspect this is wrong, because: 

mxfReader.getEssenceTypes() calls this.getHeaderPartition().getEssenceTypes();
HeaderPartition.getEssenceTypes contains this if statement:
        if(this.hasCDCIPictureEssenceDescriptor() || this.hasRGBAPictureEssenceDescriptor()){
            essenceTypes.add(EssenceTypeEnum.MainImageEssence);
        }

this.hasRGBAPictureEssenceDescriptor() should be true, although it's false, because in HeaderPartition constructor, while processing KLV packets, although there is RGBAPictureEssenceDescriptor in parsedInterchangeObjectBOs collection, and later the corresponding Node in nodeList and resolvedList, while loop at the end of the constructor does not contain any if statement like if(interchangeObjectBO.getClass().getEnclosingClass().equals(RGBAPictureEssenceDescriptor.class), so when the interchangeObjectBO contains RGBAPictureEssenceDescriptor to be processed, it gets dropped instead of getting cached.

**Comment by rpuri-netflix** [comment]
@janbella 

Thanks for pointing out this issue. https://github.com/Netflix/photon/releases/tag/v0.2.10 should contain a fix for the same (Corresponding commit goes as: https://github.com/Netflix/photon/commit/90b69933717b793c209d737384086db06f0fc652)
