### ISSUE TITLE
Stating Photon as a web service

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [Netflix/photon#65]
Hello,

I want to know how to be able to launch this project as a service, and use the RESTful web interface.
Because in the project, we can found this [file](https://github.com/Netflix/photon/blob/master/src/main/java/com/netflix/imflibrary/RESTfulInterfaces/IMPValidator.java) with very interesting features, but who to access it via an API ?

I can help with description of setup or something like that.

Thanks

**Comment by schakrovorthy** [comment]
Marc,

The intent of the IMPValidator API is to serve as an interface that can be
used to access all of the Photon's functionality from a WebService. Thanks
a lot for offering your help, we intend to build a Web Service around
Photon in the future, once that project is completed we can work on the
description and setup.

Regards
Sreeram

**Comment by cconcolato** [comment]
For now, the API being stateless, it allows anyone to write a service based on it. We do not intend to provide one open-source version but if anyone wants to contribute, we'll consider it.
